In [1]:
# import
from keras.datasets import mnist
import numpy as np
import os

Using TensorFlow backend.


In [2]:
# Chargement des données
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
# shape des data
X_train.shape

(60000, 28, 28)

In [4]:
# reshape (2d)
X_train = X_train.reshape(60000,-1)
X_test = X_test.reshape(10000,-1)

In [6]:
# création modele foret aleatoire
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [8]:
# matrice de confusion
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[ 971,    0,    0,    0,    0,    1,    3,    1,    4,    0],
       [   0, 1124,    2,    2,    0,    1,    4,    0,    1,    1],
       [   6,    1,  996,    5,    4,    1,    4,   10,    5,    0],
       [   0,    0,    9,  971,    0,    8,    0,    8,   11,    3],
       [   1,    0,    2,    0,  956,    0,    5,    0,    2,   16],
       [   3,    0,    1,   13,    3,  858,    6,    2,    5,    1],
       [   7,    3,    2,    0,    2,    4,  936,    0,    4,    0],
       [   2,    4,   20,    0,    2,    0,    0,  990,    1,    9],
       [   3,    0,    5,    8,    4,    5,    3,    3,  931,   12],
       [   5,    6,    2,   13,   11,    2,    1,    3,    7,  959]])

In [9]:
# Accuracy
accuracy_score(y_test, y_pred)

0.9692

In [11]:
# On exporte le modele avec Pickle
import pickle
pickle.dump(model,open('model.save','wb'))

In [19]:
X_test.shape


(10000, 784)

In [20]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [21]:
y_pred

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)